export const TRANSCRIPTION_IN_PROGRESS = "Transcription in progress. Please wait.";
export const BEDROCK_QUESTION_IN_PROGRESS = "Please wait while Bedrock answers your question.";
export const CONFIGURE_DEFAULT_MODEL = "Chose a model or use the default configured.";
export const CONFIGURE_SUMMARY_MODEL = "Optional - Chose a different model to get a different summary output.";
export const BEDROCK_FOLLOW_UP_WAIT = "\n\n\nPlease wait while your follow up question is answered....";
export const RECORDING_NOT_TRANSCRIBED = "Recording not transcribed. Use the icon in the table to transcribe your recording.";
export const TRANSCRIBE_OFF = "Off - Transcribe later using the transcribe button in the table below";
export const TRANSCRIBE_ON = "On - Transcribe after the recording is saved";
export const TRANSCRIPTION_FAILED = "Something went wrong. Please contact the developer.";